@startuml
!include style.puml
skinparam ArrowFontStyle plain

mainframe sd Execute delete command

box Logic LOGIC_COLOR_T1
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Module" as Module MODEL_COLOR
participant "model:Model" as Model MODEL_COLOR
end box
[->  DeleteCommand : execute(model)
activate DeleteCommand

DeleteCommand -> Model : checkDbValidModuleCode("CS3230")
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : getModule("CS3230")
activate Model

Model --> DeleteCommand : targetMod
deactivate Model

DeleteCommand -> Model : deleteModule(targetMod)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

[<--DeleteCommand : result
deactivate DeleteCommand
@enduml
